### ISSUE TITLE
Trained model

### ISSUE THREAD

**Issue by iveveive** [JuanFMontesinos/VoViT#2]
Hi, I would like to ask if it is possible to expose the trained model, I would appreciate it if so. Because running the demo requires a trained model.

**Comment by JuanFMontesinos** [comment]
As it is explained in the Readme, the weights are provided in the "release" package. https://github.com/JuanFMontesinos/VoViT/releases/tag/Speech

You simple need to move the weights to the corresponding folder. As those are >100 Mb, they cannot be uploaded to the repo itself.
