### ISSUE TITLE
flerken version

### ISSUE THREAD

**Issue by ahmadikalkhorani** [JuanFMontesinos/VoViT#4]
running `python inference_interview.py` raises the following error, which is probably due to flerken version incompatibility. I checked other versions but none of them has the requirement kwargs:

.../site-packages/flerken/models/UNet.py", line 287, in add_decoder
    TransitionBlock(self.dim[i], self.dim[i - 1], useBN=self.useBN,
TypeError: __init__() got an unexpected keyword argument 'mode'

**Comment by JuanFMontesinos** [comment]
Hi, sorry for that. Flerken is a bit messy.
I've moved the UNet used to the core model, so that it no longer depends on flerken. If you pull it should be working (I hope)

Best
Juan
